/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package converter;


import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import javax.swing.JOptionPane;
/**
 *
 * @author foufou
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form LatexToXmlForm
     */
    public MainForm() {
        initComponents();

        Console console = new Console();
        console.run();
        LatexFilePath.setText("C:\\Users\\foufou\\Documents\\NetBeansProjects\\QuizConverter\\quizW4[2075].tex.txt");
        ClassFilePath.setText("C:\\Users\\foufou\\Documents\\NetBeansProjects\\WebApplication1\\test\\sum.java");
        TestClassFilePath.setText("C:\\Users\\foufou\\Documents\\NetBeansProjects\\WebApplication1\\test\\sumTest.java");
        LatexOutputFilePath.setText("D:\\LatexQuiz.xml");
        ClassOutputFilePath.setText("D:\\CodeRunnerQuiz.xml");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LatexFC = new javax.swing.JButton();
        LatexFilePath = new javax.swing.JTextField();
        ConvertLatex = new javax.swing.JButton();
        CancelConvertLatex = new javax.swing.JButton();
        ConvertCR = new javax.swing.JButton();
        CancelConvertCR = new javax.swing.JButton();
        ClassFilePath = new javax.swing.JTextField();
        ClassFC = new javax.swing.JButton();
        TestClassFC = new javax.swing.JButton();
        TestClassFilePath = new javax.swing.JTextField();
        LatexOutputFilePath = new javax.swing.JTextField();
        LatexOutputFC = new javax.swing.JButton();
        CROutputFC = new javax.swing.JButton();
        ClassOutputFilePath = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LatexFC.setText("Latex File");
        LatexFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LatexFCActionPerformed(evt);
            }
        });

        LatexFilePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LatexFilePathActionPerformed(evt);
            }
        });

        ConvertLatex.setText("Convert");
        ConvertLatex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertLatexActionPerformed(evt);
            }
        });

        CancelConvertLatex.setText("cancel");
        CancelConvertLatex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelConvertLatexActionPerformed(evt);
            }
        });

        ConvertCR.setText("Convert");
        ConvertCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertCRActionPerformed(evt);
            }
        });

        CancelConvertCR.setText("cancel");
        CancelConvertCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelConvertCRActionPerformed(evt);
            }
        });

        ClassFilePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassFilePathActionPerformed(evt);
            }
        });

        ClassFC.setText("Java Class");
        ClassFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassFCActionPerformed(evt);
            }
        });

        TestClassFC.setText("Java Test Class");
        TestClassFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TestClassFCActionPerformed(evt);
            }
        });

        TestClassFilePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TestClassFilePathActionPerformed(evt);
            }
        });

        LatexOutputFilePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LatexOutputFilePathActionPerformed(evt);
            }
        });

        LatexOutputFC.setText("Destination Path\\name");
        LatexOutputFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LatexOutputFCActionPerformed(evt);
            }
        });

        CROutputFC.setText("Destination Path\\name");
        CROutputFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CROutputFCActionPerformed(evt);
            }
        });

        ClassOutputFilePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassOutputFilePathActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(TestClassFC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ClassFC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LatexFC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LatexOutputFC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CROutputFC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ClassFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LatexFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TestClassFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LatexOutputFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClassOutputFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ConvertLatex)
                            .addComponent(ConvertCR))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CancelConvertLatex)
                            .addComponent(CancelConvertCR))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LatexFC)
                    .addComponent(LatexFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LatexOutputFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LatexOutputFC))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelConvertLatex)
                    .addComponent(ConvertLatex))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClassFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClassFC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TestClassFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TestClassFC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CROutputFC)
                    .addComponent(ClassOutputFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConvertCR)
                    .addComponent(CancelConvertCR))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LatexFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LatexFCActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String path = f.getAbsolutePath();
        LatexFilePath.setText(path);
    }//GEN-LAST:event_LatexFCActionPerformed

    private void LatexFilePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LatexFilePathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LatexFilePathActionPerformed

    private void CancelConvertLatexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelConvertLatexActionPerformed
        // TODO add your handling code here:
        LatexFilePath.setText("");
        LatexOutputFilePath.setText("");
    }//GEN-LAST:event_CancelConvertLatexActionPerformed

    private void ConvertLatexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertLatexActionPerformed
        // TODO add your handling code here:
        if(("".equals(LatexFilePath.getText()))||(LatexFilePath.getText() == null)){
            JOptionPane.showMessageDialog(null, "Please enter the path of the source/Latex file");
        }else if(("".equals(LatexOutputFilePath.getText()))||(LatexOutputFilePath.getText() == null)){
            JOptionPane.showMessageDialog(null, "Please enter the destination of the output/Xml file");
        }else {
            String stin = LatexFilePath.getText();
            String stout = LatexOutputFilePath.getText();
            ConvertLatex cL = new ConvertLatex(stin, stout);
        }      
    }//GEN-LAST:event_ConvertLatexActionPerformed

    private void ConvertCRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertCRActionPerformed
        // TODO add your handling code here:
        if(("".equals(ClassFilePath.getText()))||(ClassFilePath.getText() == null)){
            JOptionPane.showMessageDialog(null, "Please enter the path of the Java Class");
        }else if(("".equals(TestClassFilePath.getText()))||(TestClassFilePath.getText() == null)){
            JOptionPane.showMessageDialog(null, "Please enter the path of the Java Test Class");
        }else if(("".equals(ClassOutputFilePath.getText()))||(ClassOutputFilePath.getText() == null)){
            JOptionPane.showMessageDialog(null, "Please enter the destination of the output/Xml file");
        }else {
            String Classpath = ClassFilePath.getText();
            String Testpath = TestClassFilePath.getText();
            String Outputpath = ClassOutputFilePath.getText();
            try {
                ConvertJava cJ = new ConvertJava(Classpath, Testpath, Outputpath);

            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_ConvertCRActionPerformed

    private void CancelConvertCRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelConvertCRActionPerformed
        // TODO add your handling code here:
        ClassFilePath.setText("");
        TestClassFilePath.setText("");
        ClassOutputFilePath.setText("");
    }//GEN-LAST:event_CancelConvertCRActionPerformed

    private void ClassFilePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassFilePathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClassFilePathActionPerformed

    private void ClassFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassFCActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String path = f.getAbsolutePath();
        ClassFilePath.setText(path);
    }//GEN-LAST:event_ClassFCActionPerformed

    private void TestClassFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TestClassFCActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String path = f.getAbsolutePath();
        TestClassFilePath.setText(path);
    }//GEN-LAST:event_TestClassFCActionPerformed

    private void TestClassFilePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TestClassFilePathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TestClassFilePathActionPerformed

    private void LatexOutputFilePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LatexOutputFilePathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LatexOutputFilePathActionPerformed

    private void LatexOutputFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LatexOutputFCActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String path = f.getAbsolutePath();
        LatexOutputFilePath.setText(path);
    }//GEN-LAST:event_LatexOutputFCActionPerformed

    private void CROutputFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CROutputFCActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String path = f.getAbsolutePath();
        ClassOutputFilePath.setText(path);
    }//GEN-LAST:event_CROutputFCActionPerformed

    private void ClassOutputFilePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassOutputFilePathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClassOutputFilePathActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold> 
        //</editor-fold> 

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CROutputFC;
    private javax.swing.JButton CancelConvertCR;
    private javax.swing.JButton CancelConvertLatex;
    private javax.swing.JButton ClassFC;
    private javax.swing.JTextField ClassFilePath;
    private javax.swing.JTextField ClassOutputFilePath;
    private javax.swing.JButton ConvertCR;
    private javax.swing.JButton ConvertLatex;
    private javax.swing.JButton LatexFC;
    private javax.swing.JTextField LatexFilePath;
    private javax.swing.JButton LatexOutputFC;
    private javax.swing.JTextField LatexOutputFilePath;
    private javax.swing.JButton TestClassFC;
    private javax.swing.JTextField TestClassFilePath;
    // End of variables declaration//GEN-END:variables
}
